
spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:file:./mydatabase
    driver-class-name: org.h2.Driver
    username: sa
    password:
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  sql:
    init:
      platform: h2
  jdbi:
    enabled: false
  h2:
    console:
      enabled: true
springdoc:
  swagger-ui:
      path: swagger-ui.html
server:
  port: 3052
