package io.irrigation.task.model.enums;

public enum CropType {

	CROP_MANGO, CROP_BANANA, CROP_TOMATO, CROP_APPLE, CROP_ORANGE, CROP_PINEAPPLE, CROP_WATERMELON, CROP_STRAWBERRY,
	CROP_BLUEBERRY, CROP_RASPBERRY, CROP_PEPPER, CROP_ONION, CROP_CARROT, CROP_CABBAGE, CROP_BROCCOLI, CROP_SPINACH,
	CROP_KALE, CROP_LETTUCE, CROP_AVOCADO, CROP_GRAPEFRUIT, CROP_LEMON, CROP_LIME, CROP_PEAR, CROP_PEACH, CROP_PLUM,
	CROP_CHERRY, CROP_KIWI, CROP_GRAPE, CROP_BERRY, CROP_MELON, CROP_CANTALOUPE, CROP_HONEYDEW, CROP_CUCUMBER,
	CROP_ZUCCHINI, CROP_SQUASH, CROP_EGGPLANT, CROP_POTATO, CROP_SWEET_POTATO, CROP_WHEAT, CROP_RICE, CROP_CORN,
	CROP_SOYBEAN

}
